name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - run: chsh -s /bin/bash
      - uses: actions/checkout@v2
      - uses: education/autograding@v1
