name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - run: echo $0
      - run: printenv
      - name: testingSettingVarShell
        run: SHOT=("rock" "paper" "scissors"); echo ${SHOT[$RANDOM % ${#SHOT[@]} ]};
      - name: testingSettingVarBash
        shell: bash
        run: SHOT=("rock" "paper" "scissors"); echo ${SHOT[$RANDOM % ${#SHOT[@]} ]};
      - uses: actions/checkout@v2
      - uses: education/autograding@v1
