name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - name: settingBash
        run: bash --noprofile --norc -eo pipefail {0}
      - run: printenv
      - uses: actions/checkout@v2
      - uses: education/autograding@v1
