name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    defaults:
       run:
          shell: bash --noprofile --norc -eo pipefail {0}
    steps:
      - name: EnvPrint
        run: echo $0
      - run: printenv
      - uses: actions/checkout@v2
      - uses: education/autograding@v1
