name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bash Command Lines for GitHub Actions
        # You may pin to the exact commit or the version.
        # uses: jdickey/bash@bc09809bde62634bf1f6fdfc820428e7ac10eea4
        uses: jdickey/bash@v.1.1.1
      - uses: education/autograding@v1
