name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: classroom
    steps:
      - run: echo $SHELL
      - uses: actions/checkout@v2
      - uses: education/autograding@v1
